version: "3.9"
services:
  postgre:
      container_name: postgre-db
      image: postgres:latest
      volumes:
        - "./storages/postgre:/var/postgre"
      networks:
        - appnet

  nginx:
    container_name: nginx-server
    build:
      dockerfile: docker/nginx/Dockerfile
    ports: 
      - '8888:80'
    volumes:
      - "./config/nginx/nginx.conf:/etc/nginx/nginx.conf"
    networks:
      - appnet

  app:
    container_name: python-app
    build:
      context: ./docker/python
    volumes:
      - "./app:/app"
    networks:
      - appnet

networks:
  appnet:
    

    