version: "3.9"
services:
  app:
    container_name: python-app
    build:
      context: .
      dockerfile: docker/postgre/Dockerfile
    volumes:
      - "./app:/var/www/html"
    networks:
      - appnet

  nginx:
    container_name: nginx-server
    build:
      dockerfile: docker/nginx/Dockerfile
    ports: 
      - '8800:80'
    volumes:
      - "./config/nginx/nginx.conf:/etc/nginx/nginx.conf"
    networks:
      - appnet

  postgre:
      container_name: postgre-db
      image: postgre:latest
      ports: 
        - '8800:80'
      volumes:
        - "./storages/postgre:/var/postgre"
      networks:
        - appnet

networks:
  appnet:
    

    